In [13]:
import numpy as np
train_set = np.load('hw3_material/svm/task4/train_set.npy') 
train_lbs = np.load('hw3_material/svm/task4/train_labels.npy')

test_set = np.load('hw3_material/svm/task4/test_set.npy')
test_labels = np.load('hw3_material/svm/task4/test_labels.npy')


In [14]:
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [15]:
no_of_samples, x, y = test_set.shape
test_set = test_set.reshape((no_of_samples,x*y))

no_of_samples, x, y = train_set.shape
train_set = train_set.reshape((no_of_samples,x*y))


[0.7019608  0.69411767 0.72549021 ... 0.30588236 0.29019609 0.29803923]


In [16]:
#item 1
clf = SVC(kernel='rbf', C=1)
clf = clf.fit(train_set, train_lbs)
predictions = clf.predict(test_set)
print("Test Accuracy:",metrics.accuracy_score(test_labels, predictions))
print("Confusion Matrix:\n",metrics.confusion_matrix(test_labels, predictions))

Test Accuracy: 0.95
Confusion Matrix:
 [[  0  50]
 [  0 950]]


In [29]:
#item 2

class0 = 0
class1 = 0

new_train_set = train_set
new_train_lbs = train_lbs

for label in train_lbs:
    if(label == 0):
        class0 += 1
    elif(label == 1):
        class1 += 1
        
if (class0 < class1):
    min_class = 0
elif (class1 < class0):
    min_class = 1

diff = abs(class0-class1)

while(diff > 3):
    for i in range(np.size(new_train_lbs)):
        if(diff > 3):
            if(new_train_lbs[i] == min_class):
                new_train_lbs = np.append(new_train_lbs, new_train_lbs[i])
                new_train_set = np.append(new_train_set, [new_train_set[i]], axis = 0)
                diff -= 1

clf = SVC(kernel='rbf', C=1)
clf = clf.fit(new_train_set, new_train_lbs)
predictions = clf.predict(test_set)
print("Test Accuracy:",metrics.accuracy_score(test_labels, predictions))
print("Confusion Matrix:\n",metrics.confusion_matrix(test_labels, predictions))

Test Accuracy: 0.951
Confusion Matrix:
 [[ 12  38]
 [ 11 939]]


In [31]:
#item 3

class0 = 0
class1 = 0

new_train_set = train_set
new_train_lbs = train_lbs

for label in train_lbs:
    if(label == 0):
        class0 += 1
    elif(label == 1):
        class1 += 1
        
if (class0 > class1):
    max_class = 0
elif (class1 > class0):
    max_class = 1

diff = abs(class0-class1)

while(diff > 3):
    for i in range(np.size(new_train_lbs)):
        if(i < np.size(new_train_lbs)):
            if(diff > 3):
                if(new_train_lbs[i] == max_class):
                    new_train_lbs = np.delete(new_train_lbs, i)
                    new_train_set = np.delete(new_train_set, i, axis = 0)
                    diff -= 1

clf = SVC(kernel='rbf', C=1)
clf = clf.fit(new_train_set, new_train_lbs)
predictions = clf.predict(test_set)
print("Test Accuracy:",metrics.accuracy_score(test_labels, predictions))
print("Confusion Matrix:\n",metrics.confusion_matrix(test_labels, predictions))

Test Accuracy: 0.789
Confusion Matrix:
 [[ 36  14]
 [197 753]]


In [8]:
#item 4
clf = SVC(kernel='rbf', C=1, class_weight='balanced')
clf = clf.fit(train_set, train_lbs)
predictions = clf.predict(test_set)
print("Test Accuracy:",metrics.accuracy_score(test_labels, predictions))
print("Confusion Matrix:\n",metrics.confusion_matrix(test_labels, predictions))

Test Accuracy: 0.936
Confusion Matrix:
 [[ 16  34]
 [ 30 920]]
